//@version=3
study(shorttitle="[nv] PC ", title="PC Ratio SP", overlay=false)
length = input(20, minval=1)
src = input(close, title="Source")
mult = input(2.0, minval=0.001, maxval=50)



PCI = security('USI:PCSPX', period, close) 




basis = sma(PCI, length)
dev = mult * stdev(PCI, length)
upper = basis + dev
lower = basis - dev
plot(basis, color=red)
p1 = plot(upper, color=blue)
p2 = plot(lower, color=blue)


plot(PCI, linewidth=2, color=red)
