study(title='[nv] EURUSD Rate Comparative Strenght Index', overlay=false)

fast_ema_input = input(defval=21, title = 'Fast Line', type=integer)
slow_ema_input = input(defval=26, title = 'Slow Line', type=integer)
smoothing = input(defval=26, title = 'Smoothing', type=integer)

EURUSD = security('EURUSD', period, close)
EURGBP = security('EURGBP', period, close)
EURAUD = security('EURAUD', period, close)
EURJPY = security('EURJPY', period, close)
EURCHF = security('EURCHF', period, close)
EURCAD = security('EURCAD', period, close)
EURNZD = security('EURNZD', period, close)

USDEUR = security('USDEUR', period, close)
USDGBP = security('USDGBP', period, close)
USDAUD = security('USDAUD', period, close)
USDJPY = security('USDJPY', period, close)
USDCHF = security('USDCHF', period, close)
USDCAD = security('USDCAD', period, close)
USDNZD = security('USDNZD', period, close)


EURUSD_EMA_FAST = roc(EURUSD, fast_ema_input)
EURGBP_EMA_FAST = roc(EURGBP, fast_ema_input)
EURAUD_EMA_FAST = roc(EURAUD, fast_ema_input)
EURJPY_EMA_FAST = roc(EURJPY, fast_ema_input)
EURCHF_EMA_FAST = roc(EURCHF, fast_ema_input)
EURCAD_EMA_FAST = roc(EURCAD, fast_ema_input)
EURNZD_EMA_FAST = roc(EURNZD, fast_ema_input)

USDEUR_EMA_FAST = roc(USDEUR, fast_ema_input)
USDGBP_EMA_FAST = roc(USDGBP, fast_ema_input)
USDAUD_EMA_FAST = roc(USDAUD, fast_ema_input)
USDJPY_EMA_FAST = roc(USDJPY, fast_ema_input)
USDCHF_EMA_FAST = roc(USDCHF, fast_ema_input)
USDCAD_EMA_FAST = roc(USDCAD, fast_ema_input)
USDNZD_EMA_FAST = roc(USDNZD, fast_ema_input)


EUR_close = ( EURUSD+ EURGBP+ EURAUD+ EURJPY+ EURCHF+ EURCAD+ EURNZD ) / 7
EUR_roc = ( EURUSD_EMA_FAST + EURGBP_EMA_FAST + EURAUD_EMA_FAST + EURJPY_EMA_FAST + EURCHF_EMA_FAST + EURCAD_EMA_FAST + EURNZD_EMA_FAST ) / 7
EUR_distance = sma(EUR_close - EUR_roc, smoothing)

USD_close = ( USDEUR+ USDGBP+ USDAUD+ USDJPY+ USDCHF+ USDCAD+ USDNZD ) / 7
USD_roc = ( USDEUR_EMA_FAST + USDGBP_EMA_FAST + USDAUD_EMA_FAST + USDJPY_EMA_FAST + USDCHF_EMA_FAST + USDCAD_EMA_FAST + USDNZD_EMA_FAST ) / 7
USD_distance = sma(USD_close - USD_roc, smoothing)

EUR_roc_smoothed = sma(EUR_roc, smoothing)
USD_roc_smoothed = sma(USD_roc, smoothing)

plot_EUR = plot (EUR_roc_smoothed, linewidth=2, title='Euro', color=red )
plot_USD = plot (USD_roc_smoothed, linewidth=2, title='Dollar', color=green )

hline(0, title='Zero Line')