study(title='[nv]RSI-PLUS', overlay=false)

rsi_day = rsi(security(tickerid, "D", ohlc4), 28)
rsi_week = rsi(security(tickerid, "W", ohlc4), 52)
rsi_month = rsi(security(tickerid, "M", ohlc4), 28)
rsi_year = rsi(security(tickerid, "12M", ohlc4), 12)

rsi_result = (rsi_day + rsi_week + rsi_month + rsi_year) / 4

plot(rsi_result, linewidth=2, color = orange)

hline(20)
hline(80)
// -------------------------------------------------
// study(title="Relative Strength Index", shorttitle="RSI")
src = security(tickerid, "W", ohlc4), len = input(11, minval=1, title="Length")
up = rma(max(change(src), 0), len)
down = rma(-min(change(src), 0), len)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))

plot(ema(rsi,3), color=purple, linewidth=2, transp=1)

rsi_ema = ema(rsi, 20)

plot(rsi_ema,color=blue, linewidth=2, transp=1)


band1 = hline(70)
band0 = hline(30)
fill(band1, band0, color=purple, transp=90)