//@version=3
//By Glaz
//Modifications:
// Added Columns to show when signal is outside of Thresh Hold Channnel.
// Set default Parameters to match QQE Cross Alert indicator.
//
study("QQE MT4 Glaz-modified by nvFede")
RSI_Period = input(14,title='RSI Length')
SF = input(5,title='RSI Smoothing')
QQE=input(4.238,title='Fast QQE Factor')
ThreshHold=input(10,title="Thresh-hold")

src = input(close,title="RSI Source")

Wilders_Period = RSI_Period * 2 - 1

Rsi = rsi(src,RSI_Period)
RsiMa = sma(Rsi, SF)
AtrRsi = abs(RsiMa[1] - RsiMa)
MaAtrRsi = ema(AtrRsi, Wilders_Period)
dar = ema(MaAtrRsi,Wilders_Period) * QQE

longband = 0.0
shortband=0.0
trend = 0

DeltaFastAtrRsi= dar
RSIndex=RsiMa
newshortband=  RSIndex + DeltaFastAtrRsi
newlongband= RSIndex - DeltaFastAtrRsi
longband := RSIndex[1] > longband[1] and RSIndex > longband[1]? max(longband[1],newlongband):newlongband
shortband := RSIndex[1] < shortband[1] and  RSIndex < shortband[1]? min(shortband[1], newshortband):newshortband
trend := cross(RSIndex, shortband[1])?1:cross(longband[1], RSIndex)?-1:nz(trend[1],1)
FastAtrRsiTL = trend==1? longband: shortband

// Find all the QQE Crosses
QQExlong  = 0, QQExlong := nz(QQExlong[1])
QQExshort = 0, QQExshort := nz(QQExshort[1])
QQExlong  :=  FastAtrRsiTL< RSIndex ? QQExlong+1 : 0
QQExshort :=  FastAtrRsiTL> RSIndex ? QQExshort+1 : 0
// Zero cross
QQEzlong  = 0, QQEzlong := nz(QQEzlong[1])
QQEzshort = 0, QQEzshort := nz(QQEzshort[1])
QQEzlong  :=  RSIndex>=50 ? QQEzlong+1 : 0
QQEzshort :=  RSIndex<50 ? QQEzshort+1 : 0
//
// Thresh Hold channel Crosses give the BUY/SELL alerts.
QQEclong  = 0, QQEclong := nz(QQEclong[1])
QQEcshort = 0, QQEcshort := nz(QQEcshort[1])
QQEclong  := RSIndex>(50+ThreshHold) ? QQEclong+1 : 0
QQEcshort := RSIndex<(50-ThreshHold) ? QQEcshort+1 : 0


hcolor = (RsiMa-50)>ThreshHold? green : (RsiMa-50)<0-ThreshHold ? red : orange
plot(FastAtrRsiTL-50,color=blue,transp=0,linewidth=2)
p1=plot(RsiMa-50,color=orange,transp=0,linewidth=2)


hZero = hline(0,color=black,linestyle=dashed,linewidth=1)
hUpper= hline(ThreshHold,color=green,linestyle=dashed,linewidth=2)
hLower= hline(0-ThreshHold,color=red,linestyle=dashed,linewidth=2)
fill(hUpper,hLower,color=gray,transp=80)
//EOF
