 // Created by Fede on 8/30/2014
// Updated - 03/22/2014

study(title="WAVES DEMA", shorttitle="WAVES-D", precision = 2)


make_hull(src,length) =>
	hullma = wma(2*wma(src, length/2)-wma(src, length), round(sqrt(length)))


usewa = input(true, title = "Wave A", type=bool)
usewb = input(true, title = "Wave B", type=bool)
usewc = input(true, title = "Wave C", type=bool)

// WAVE CALC
// Wave A
fastMA1 = usewa ? make_hull(close, 8) : na
slowMA1 = usewa ? make_hull(close, 34) : na
macd1 =  usewa ? fastMA1 - slowMA1 : na
signal1 =  usewa ? make_hull(macd1, 34) : na
hist1 =  usewa ? macd1 - signal1 : na

fastMA2 = usewa ? make_hull(close, 8) : na
slowMA2 = usewa ? make_hull(close, 55) : na
macd2 = usewa ? fastMA2 - slowMA2 : na
signal2 = usewa ? make_hull(macd2, 55) : na
hist2 = usewa ? macd2 - signal2 : na

// Wave B
fastMA3 = usewb ? make_hull(close, 8) : na
slowMA3 = usewb ? make_hull(close, 89) : na
macd3 = usewb ? fastMA3 - slowMA3 : na
signal3 = usewb ? make_hull(macd3, 89) : na
hist3 = usewb ? macd3 - signal3 : na

fastMA4 = usewb ? make_hull(close, 8) : na
slowMA4 = usewb ? make_hull(close, 144) : na
macd4 = usewb ? fastMA4 - slowMA4 : na
signal4 = usewb ? make_hull(macd4, 144) : na
hist4 = usewb ? macd4 - signal4 : na

// Wave C
fastMA5 = usewc ? make_hull(close, 8) : na
slowMA5 = usewc ? make_hull(close, 233) : na
macd5 = usewc ? fastMA5 - slowMA5 : na
signal5 = usewc ? make_hull(macd5, 233) : na
hist5 = usewc ? macd5 - signal5 : na

fastMA6 = usewc ? make_hull(close, 8) : na
slowMA6 = usewc ? make_hull(close, 377) : na
macd6 = usewc ? fastMA6 - slowMA6 : na

// PLOTs
plot(macd6, color=#FF0000, style=line, title="Wave C1", linewidth=3)
plot(hist5, color=#FF8C00, style=line, title="Wave C2", linewidth=3)

plot(hist4, color=#FF00FF, style=line, title="Wave B1", linewidth=3)
plot(hist3, color=#0000FF, style=line, title="Wave B2", linewidth=3)

plot(hist2, color=#008000, style=line, title="Wave A1", linewidth=3)
plot(hist1, color=#DAA520, style=line, title="Wave A2", linewidth=3)

hline(0, color=white, title = "Zero Line", linewidth = 2, linestyle = dashed)