//@version=4
study(title="BB Volume", overlay=true, format=format.volume, precision=0, scale=scale.none)
length = input(21, minval=1)
src = input(close, title="Source")
mult = input(2.0, minval=0.001, maxval=50)
basis = sma(src, length)
dev = mult * stdev(src, length)
upper = basis + dev
lower = basis - dev

vol = volume * vwap

showMA = input(true, title="Show MA ?")

bull_color = #058ac5
indecision_color = #dde4c5
bear_color = #ff583e

colors = hl2 > basis and hl2 <= upper ? bull_color : hl2 < basis and hl2 >= lower ? bear_color : indecision_color

plot(vol, style=plot.style_columns, transp=5, color=colors)

plot(showMA ? sma(vol,length) : na , color=color.green)
