//@version=4
study(title = "QS Advanced Coppock Curve", overlay=false)

wmaLength = input(title="WMA Length", type=input.integer, defval=7)
longRoCLength = input(title="Long RoC Length", type=input.integer, defval=14)
shortRoCLength = input(title="Short RoC Length", type=input.integer, defval=11)
factorSmoothness = input(title="Smoothness", type=input.integer, defval=3)
//hma(_src, _length)=>
  //  wma((2 * wma(_src, _length / 2)) - wma(_src, _length), round(sqrt(_length)))

source = close

curve = hma(roc(source, longRoCLength) + roc(source, shortRoCLength), wmaLength)

media = sma(curve, 21)


hline(0)


curveColor=curve > 0 ? color.green : color.red
plot(sma(curve,factorSmoothness), color = curve > media ? color.green : color.red, linewidth=3, transp=50)
plot(sma(curve,factorSmoothness), color = curveColor)
//plot(media, color = curve > media ? color.green : color.red, linewidth=3)

plot(sma(curve,factorSmoothness), style=plot.style_area, transp=50, color=curveColor)

hBand = media + stdev(media,21)
lBand = media - stdev(media,21)

plot(hBand, color=color.yellow,linewidth=1, style=plot.style_circles)
plot(lBand, color=color.yellow,linewidth=1, style=plot.style_circles)
//fill(hBand, lBand, color=color.white)

// Alerts
buySignal = crossover(curve, 0)
if buySignal
    alert("Buy signal Coppock")

sellSignal = crossunder(curve, 0)
if sellSignal
    alert("Sell signal Coppock")
