//@version=3
study("QS - Noya Oscillator")
bull_color = #058ac5
indecision_color = #dde4c5
bear_color = #ff583e
l=252
length = input(21, minval=0)
smoothness = input(5, minval=0)
stock = security(tickerid, period, close)
risk_free = security(input("TNX"), period, close)
benchmark = security(input('SPX'), period, close)
sector = security(input('XLK'), period, close)

stock_ret = log(stock/stock[1])
benchmark_ret = log(benchmark/benchmark[1])
sector_ret = log(sector/sector[1])

stock_ret_mean = wma(stock_ret, length)
benchmark_ret_mean = wma(benchmark_ret, length)
sector_ret_mean = wma(sector_ret, length)

stock_std = stdev(stock_ret, length)
benchmark_std = stdev(benchmark_ret, length)
sector_std = stdev(sector_ret, length)

NRU =( (stock_ret_mean - benchmark_ret_mean) + (stock_ret_mean - sector_ret_mean)  )* l
NRD =( (stock_std - benchmark_std) + (stock_std - sector_std) ) * sqrt(l)

NR = wma( NRU / NRD , smoothness )



plot(NR * 10, style=histogram, color=NR > 0? bull_color : bear_color)
hline(0, color=indecision_color)
