study("QS Adaptative Oscillator", overlay=false)

length = input(21, minval=1)
src = input(hl2, type=source)
smoothness = input(5)
reverse = input(10)

make_kama(x, y) =>
    xvnoise = abs(x - x[1])
    nfastend = 0.666
    nslowend = 0.0645
    nsignal = abs(x - x[y])
    nnoise = sum(xvnoise, y)
    nefratio = iff(nnoise != 0, nsignal / nnoise, 0)
    nsmooth = pow(nefratio * (nfastend - nslowend) + nslowend, 2)
    KAMA = nz(KAMA[1]) + nsmooth * (x - nz(KAMA[1]))

ma = make_kama(src, length)

osc = linreg(close - ma, smoothness, 0)
osc_color = osc > 0 ? green : red

osc_reverse = make_kama(osc, reverse)

plot(osc, color=osc_color, style=columns, title="KAMA")
plot(osc_reverse, color=yellow, style=line, title="KAMA")

hline(0, linestyle=dashed)
