//@version=5
indicator(title="RSI Dynamics", shorttitle="RSI Dynamics", format=format.price, precision=2, timeframe="", timeframe_gaps=true)


lengthRSI = input.int(14, "RSI Length", minval=1)

src = input(close, title="RSI Source")
rsi = ta.rsi(src, lengthRSI)

rsi_smooth = ta.sma(rsi, 5)

plot(rsi_smooth, "RSI", color=#FF6D00)

h0 = hline(75, "Upper Band", color=#787B86)
h1 = hline(25, "Lower Band", color=#787B86)

fill(h0, h1, color=color.rgb(33, 150, 243, 90), title="Background")
