
study(title="QS Trend Force", shorttitle="QS TF")


gamma = input(0.618, minval=-0.1, maxval = 0.9)
sma_length = input(21, minval=0)
regression_lenght = input(5, minval=0)



hline(0.30, color=gray, linestyle=dashed)
hline(-0.30, color=gray, linestyle=dashed)
hline(0, color=gray, linestyle=dashed)
xL0 = (1-gamma) * close + gamma * nz(xL0[1], 1)
xL1 = - gamma * xL0 + nz(xL0[1], 1) + gamma * nz(xL1[1], 1)
xL2 = - gamma * xL1 + nz(xL1[1], 1) + gamma * nz(xL2[1], 1)
xL3 = - gamma * xL2 + nz(xL2[1], 1) + gamma * nz(xL3[1], 1)
CU = (xL0 >= xL1 ? xL0 - xL1 : 0) + (xL1 >= xL2 ? xL1 - xL2 : 0)  + (xL2 >= xL3 ? xL2 - xL3 : 0)
CD = (xL0 >= xL1 ? 0 : xL1 - xL0) + (xL1 >= xL2 ? 0 : xL2 - xL1)  + (xL2 >= xL3 ? 0 : xL3 - xL2)

nRes = (iff(CU + CD != 0, CU / (CU + CD), 0)) - 0.5
trend = linreg(nRes, regression_lenght, 0)
trend_color = trend > 0 ? green : red


plot(trend, color=red, title="Trend Force", style=histogram, linewidth=3, color=trend_color)

osc_line = sma(trend, sma_length)
plot(osc_line, style=line, color=yellow, title="SMA", linewidth=3)
